### ISSUE TITLE
shad::rt::executeOnAll with std::string

### ISSUE THREAD

**Issue by plavin** [pnnl/SHAD#249]
I'm trying to call a function on every locality with a std::string as input. However, I get junk data on ranks aside from rank 0. How should I implement this so that the std::string's value is available everywhere? 

```c++
void region_enter(const std::string &str) {
  mpiP_region_enter(str.c_str()); // prints `str` to a file
}

...
const std::string rn = "region1";
shad::rt::executeOnAll(region_enter, rn);
```

**Comment by marwick4** [comment]
Hi Patrick,
Args to call back function must be copyable, and strings are not copyable.  What gets passed to the call back function is the string's address at the call site.  Since the address is not valid on other localities, you get junk.  The only way to do what you want is to store the string in a fixed size char array.  For example, to pass strings <= X characters, I store the string as charX.  Then everything works fine.
John
    On Friday, November 3, 2023 at 09:33:56 AM PDT, Patrick Lavin ***@***.***> wrote:  
 
 


I'm trying to call a function on every locality with a std::string as input. However, I get junk data on ranks aside from rank 0. How should I implement this so that the std::string's value is available everywhere?
void region_enter(const std::string &str) {
  mpiP_region_enter(str.c_str()); // prints `str` to a file
}

...
const std::string rn = "region1";
shad::rt::executeOnAll(region_enter, rn);
