### ISSUE TITLE
Travis build randomly failing tests

### ISSUE THREAD

**Issue by mminutoli** [pnnl/SHAD#5]
This is build fails the vector test but I have seen failing also the local hashmap.  My feeling is that there is something wrong in the unit tests. We need to investigate more.

[Build 21.6](https://travis-ci.org/mminutoli/SHAD/jobs/308281392)

**Comment by mminutoli** [comment]
Another instance in which the test is failing:

https://travis-ci.org/mminutoli/SHAD/jobs/327057382#L1089

**Comment by mminutoli** [comment]
Here is an instance where is the local hashmap that is failing:
https://travis-ci.org/mminutoli/SHAD/jobs/344118321#L1176

**Comment by tjstavenger-pnnl** [comment]
Some notes from our call a couple weeks ago:

In https://github.com/pnnl/SHAD/blob/master/test/unit_tests/data_structures/vector_test.cc#L402-L406, the handle is always null in my dev environment. @mminutoli believes this is due to only having one locality? Though the AsyncInsertAt was getting called multiple times.

I believe these lines are missing shad::rt::waitForCompletion calls in between the async calls: https://github.com/pnnl/SHAD/blob/master/test/unit_tests/data_structures/vector_test.cc#L410-L416

This was the most commonly failing test, though I've seen others fail too. I would guess their periodic failures are due to similar reasons.

**Comment by VitoCastellana** [comment]
For the vector, the bug was most likely in the missing waits, since the async calls were modifying the content of the data structure.

**Comment by mminutoli** [comment]
I think #27 fixes #5.  I'll open another bug for the Erase issue.
